"""initial_schema

Revision ID: cc1a1fab143e
Revises: 
Create Date: 2026-05-11 01:22:00.722897
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc1a1fab143e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###